export const config = {
    projectionScale: 310,
    scaleExtent: [0.5, 10] as [number, number],
    parisCoord: [2.3522, 48.8566] as [number, number],
    animationDuration: 800,
    legendHeight: 130,
    legendWidth: 150,
    legendMaxHeight: 250,
    legendMaxWidth: 300,
    legendHeightRatio: 1.6,
    legendYposition: 110,
    legendLabelOffset: 5,
    legendLineBaseY: 45,
    legendLineSpacing: 25,
    legendCircleBaseX: 100,
    legendCircleBaseY: 65,
    legendCircleXFactor: 50,
    countryModeExponent: 0.6,
    continentModeExponent: 0.18,
    mapStrokeWidth: 0.75,
    light: {
        validCountry: "#87ceeb",
        invalidCountry: "#d3d3d3",
        nullCountry: "#d8dee6",
    },
    dark: {
        validCountry: "#116383",
        invalidCountry: "#666",
        nullCountry: "#40404a",
    },
    arrowHeadSize: 17,
} as const;
